<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Achar.Interfaces.Reporting\Achar.Interfaces.Reporting.csproj" />
        <ProjectReference Include="..\Achar.Interfaces.Testing\Achar.Interfaces.Testing.csproj" />
    </ItemGroup>

</Project>
